using System;

namespace MauiMixTube.Generators
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.CSharp.Syntax;
    using Microsoft.CodeAnalysis.Text;


    [Generator]
    public class WebTagGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var tagged = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    "MauiMixTube.Models.WebTagProviderAttribute",
                    predicate: (node, _) => node is ClassDeclarationSyntax,
                    transform: (ctx, _) => GetTagNames(ctx))
                .Collect();

            context.RegisterSourceOutput(tagged, GenerateSource);
        }

        //private static IEnumerable<string> GetTagNames(
        //    GeneratorAttributeSyntaxContext ctx)
        //{
        //    var classNode = (ClassDeclarationSyntax)ctx.TargetNode;
        //    return classNode.Members
        //        .OfType<FieldDeclarationSyntax>()
        //        .SelectMany(f => f.Declaration.Variables)
        //        .Select(v => v.Identifier.Text);
        //}
        private static IEnumerable<string> GetTagNames(GeneratorAttributeSyntaxContext ctx)
        {
            var classNode = (ClassDeclarationSyntax)ctx.TargetNode;
            var model = ctx.SemanticModel;
            var results = new List<string>();

            foreach (var member in classNode.Members)
            {
                if (member is FieldDeclarationSyntax field)
                {
                    var typeInfo = model.GetTypeInfo(field.Declaration.Type).Type;
                    if (typeInfo?.Name == "WebTag")
                    {
                        foreach (var v in field.Declaration.Variables)
                            results.Add(v.Identifier.Text);
                    }
                }
                else if (member is PropertyDeclarationSyntax property)
                {
                    var typeInfo = model.GetTypeInfo(property.Type).Type;
                    if (typeInfo?.Name == "WebTag")
                    {
                        results.Add(property.Identifier.Text);
                    }
                }
            }
            return results;
        }

        private static void GenerateSource(
            SourceProductionContext ctx,
            System.Collections.Immutable.ImmutableArray<IEnumerable<string>> tagGroups)
        {
            var tagNames = tagGroups.SelectMany(t => t).Distinct();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("namespace MauiMixTube.Models;");
            sb.AppendLine();
            sb.AppendLine("public partial record WebTag");
            sb.AppendLine("{");

            foreach (var name in tagNames)
                sb.AppendLine($"    public static WebTag {name} => WebTagRegistry.GetByName(\"{name}\");");

            sb.AppendLine("}");

            ctx.AddSource("WebTag.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}
